service: employee-allocation-backend

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: app.main.handler
    events:
      - httpApi: '*'

custom:
  pythonRequirements:
    dockerizePip: false
    pipCmdExtraArgs:
      - "--platform"
      - "manylinux2014_x86_64"
      - "--implementation"
      - "cp"
      - "--python-version"
      - "3.11"
      - "--only-binary=:all:"