import io
import json
import os
from typing import Optional
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from fpdf import FPDF
from google import genai
from google.genai import types

router = APIRouter()

# Initialize Gemini Client (automatically picks up GEMINI_API_KEY from environment)
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

# Pydantic Schemas
class ProjectPromptRequest(BaseModel):
    category: str
    tech_stack: Optional[str] = "Python, React"
    difficulty: Optional[str] = "Intermediate"
    description: Optional[str] = ""

class SelectedProjectProposalRequest(BaseModel):
    title: str
    summary: str
    category: str
    target_audience: str


# -------------------------------------------------------------------------
# 1. GENERATE PROJECT SUGGESTIONS (JSON Output)
# -------------------------------------------------------------------------
@router.post("/suggest")
def suggest_projects(req: ProjectPromptRequest):
    prompt = f"""
    Suggest 3 unique project ideas based on these constraints:
    - Category: {req.category}
    - Tech Stack: {req.tech_stack}
    - Difficulty: {req.difficulty}
    - User Preferences: {req.description}

    Return a JSON array of objects. Each object must contain:
    - "id": number (1 to 3)
    - "title": project title string
    - "summary": 2-sentence overview
    - "category": string
    - "difficulty": string
    - "target_audience": target user base string
    """

    try:
        # Gemini forced JSON schema configuration
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.7,
            ),
        )
        
        projects = json.loads(response.text)
        return {"projects": projects}
        
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, 
            detail=f"Gemini API Error: {str(e)}"
        )


# -------------------------------------------------------------------------
# 2. GENERATE PROJECT PROPOSAL PDF
# -------------------------------------------------------------------------
@router.post("/generate-proposal-pdf")
def generate_proposal_pdf(req: SelectedProjectProposalRequest):
    prompt = f"""
    Write a detailed, highly professional Project Proposal document for:
    - Title: {req.title}
    - Category: {req.category}
    - Summary: {req.summary}
    - Target Audience: {req.target_audience}

    Format the response clearly into these sections:
    1. Executive Summary
    2. Core Features & Capabilities
    3. Technical Architecture & Tech Stack
    4. Project Timeline & Implementation Phases
    
    Use clean plain text without Markdown syntax like asterisks or hashtags.
    """

    try:
        # Call Gemini for proposal text
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(temperature=0.4),
        )
        proposal_text = response.text

        # Create PDF using FPDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Header Title
        pdf.set_font("Helvetica", style="B", size=16)
        cleaned_title = req.title.encode("latin-1", "replace").decode("latin-1")
        pdf.cell(0, 10, f"Project Proposal: {cleaned_title}", ln=True, align="C")
        
        # Header Subtitle
        pdf.set_font("Helvetica", style="I", size=10)
        pdf.cell(0, 8, f"Category: {req.category} | Audience: {req.target_audience}", ln=True, align="C")
        pdf.ln(10)

        # Content Body
        pdf.set_font("Helvetica", size=10)
        # Sanitize non-latin characters generated by LLMs (em-dashes, fancy quotes, etc.)
        sanitized_text = proposal_text.encode("latin-1", "replace").decode("latin-1")
        
        for line in sanitized_text.split("\n"):
            pdf.multi_cell(0, 6, line)

        # Output to memory buffer
        pdf_buffer = io.BytesIO()
        pdf_output = pdf.output(dest="S")
        pdf_buffer.write(pdf_output)
        pdf_buffer.seek(0)

        filename = f"Proposal_{req.title.replace(' ', '_')}.pdf"
        return StreamingResponse(
            pdf_buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={filename}"},
        )

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, 
            detail=f"Proposal generation failed: {str(e)}"
        )