import traceback
import sys
from pathlib import Path
from datetime import datetime, timezone
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, Header, status
from sqlalchemy.orm import Session
from fastapi.encoders import jsonable_encoder

from app.api.deps import get_db
from app.models import ChatQuery
from app.schemas.chat_query import ChatQueryCreate, ChatQueryResponse





ROOT_DIR = Path(__file__).resolve().parents[3]  # Adjust depth based on app location
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))
from ai_engine.agent import chat_query


router = APIRouter()


def get_current_user_id_optional(authorization: Optional[str] = Header(None)) -> Optional[str]:
    """Helper to extract user_id from Bearer token if available."""
    if not authorization or not authorization.startswith("Bearer "):
        return None
    try:
        # Replace with your JWT decoding logic if applicable:
        # token = authorization.split(" ")[1]
        # payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        # return payload.get("user_id") or payload.get("sub")
        return None
    except Exception:
        return None


@router.get("/", response_model=List[ChatQueryResponse])
def get_chat_history(
    user_id: Optional[str] = Query(None),
    limit: int = 30,
    db: Session = Depends(get_db),
    token_user_id: Optional[str] = Depends(get_current_user_id_optional)
):
    """
    Retrieve user-specific chat history.
    Orders chronologically (oldest to newest) for direct rendering into the chat window.
    """
    target_user_id = user_id or token_user_id
    if not target_user_id:
        return []

    # Query logs for specific user
    logs = (
        db.query(ChatQuery)
        .filter(ChatQuery.user_id == str(target_user_id))
        .order_by(ChatQuery.timestamp.desc())
        .limit(limit)
        .all()
    )

    # Reverse to return in chronological order (oldest -> newest)
    return list(reversed(logs))

@router.post("/", response_model=ChatQueryResponse, status_code=status.HTTP_201_CREATED)
def process_and_save_chat(
    query_in: ChatQueryCreate,
    db: Session = Depends(get_db),
    token_user_id: Optional[str] = Depends(get_current_user_id_optional)
):
    try:
        # 1. Execute AI query logic
        raw_response = chat_query(query_in.query)

        # 2. Sanitize raw_response completely using jsonable_encoder
        # This converts all date/datetime objects inside dicts/lists to ISO string representations
        safe_response = jsonable_encoder(raw_response)

        recommendations = []
        if isinstance(safe_response, dict):
            response_text = (
                safe_response.get("response_text")
                or safe_response.get("text")
                or safe_response.get("message")
                or "No response generated by AI."
            )
            recommendations = safe_response.get("recommendations", [])
        elif isinstance(safe_response, str):
            response_text = safe_response
        else:
            response_text = str(safe_response) if safe_response else "No response generated by AI."

        resolved_user_id = query_in.user_id or token_user_id or "anonymous_user"

        # 3. Generate sequential query_id
        total_queries = db.query(ChatQuery).count()
        custom_query_id = f"rp2-query-{total_queries + 1}"

        # 4. Save to Database
        chat_log = ChatQuery(
            query_id=custom_query_id,
            user_id=str(resolved_user_id),
            query_text=query_in.query,
            response_text=str(response_text),
            timestamp=datetime.now(timezone.utc)
        )

        db.add(chat_log)
        db.commit()
        db.refresh(chat_log)

        # 5. Return serializable Pydantic response model
        return ChatQueryResponse(
            id=chat_log.query_id,
            user_id=chat_log.user_id,
            query=chat_log.query_text,
            response_text=chat_log.response_text,
            recommendations=recommendations,
            created_at=chat_log.timestamp
        )

    except Exception as e:
        db.rollback()
        traceback.print_exc()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error executing chat query: {str(e)}"
        )