# app/api/chat_queries.py
from fastapi import APIRouter, Depends, status, HTTPException
from sqlalchemy.orm import Session
from typing import List, Optional
from uuid import UUID
from datetime import datetime, timezone
import traceback

from fastapi.encoders import jsonable_encoder

from app.api.deps import get_db, get_current_user_id_optional
from app.models import ChatQuery
from app.schemas.chat_query import ChatQueryResponse, ChatQueryCreate

from ai_engine.agent import chat_query

router = APIRouter()

@router.get("/", response_model=List[ChatQueryResponse])
def get_chat_history(
    user_id: Optional[str] = None,
    limit: int = 50,
    db: Session = Depends(get_db)
):
    """Retrieve chat history logs."""
    query = db.query(ChatQuery)
    if user_id:
        query = query.filter(ChatQuery.user_id == user_id)
    return query.order_by(ChatQuery.timestamp.desc()).limit(limit).all()


@router.post("/", response_model=ChatQueryResponse, status_code=status.HTTP_201_CREATED)
def process_and_save_chat(
    query_in: ChatQueryCreate,
    db: Session = Depends(get_db),
    token_user_id: Optional[str] = Depends(get_current_user_id_optional)
):
    try:
        resolved_user_id = query_in.user_id or token_user_id or "anonymous_user"

        # 1. Fetch recent conversation history for this user (last 5 exchanges),
        #    so follow-up questions like "of those, who's busy" work correctly
        recent_history = (
            db.query(ChatQuery)
            .filter(ChatQuery.user_id == str(resolved_user_id))
            .order_by(ChatQuery.timestamp.desc())
            .limit(5)
            .all()
        )
        conversation_history = [
            {"query": h.query_text, "response": h.response_text}
            for h in reversed(recent_history)
        ]

        # 2. Execute AI query logic, now WITH history
        raw_response = chat_query(query_in.query, conversation_history=conversation_history)

        # 3. Sanitize raw_response completely using jsonable_encoder
        safe_response = jsonable_encoder(raw_response)

        recommendations = []
        if isinstance(safe_response, dict):
            response_text = (
                safe_response.get("response_text")
                or safe_response.get("text")
                or safe_response.get("message")
                or "No response generated by AI."
            )
            recommendations = safe_response.get("recommendations", [])
        elif isinstance(safe_response, str):
            response_text = safe_response
        else:
            response_text = str(safe_response) if safe_response else "No response generated by AI."

        # 4. Generate sequential query_id
        total_queries = db.query(ChatQuery).count()
        custom_query_id = f"rp2-query-{total_queries + 1}"

        # 5. Save to Database
        chat_log = ChatQuery(
            query_id=custom_query_id,
            user_id=str(resolved_user_id),
            query_text=query_in.query,
            response_text=str(response_text),
            timestamp=datetime.now(timezone.utc)
        )

        db.add(chat_log)
        db.commit()
        db.refresh(chat_log)

        # 6. Return serializable Pydantic response model
        return ChatQueryResponse(
            id=chat_log.query_id,
            user_id=chat_log.user_id,
            query=chat_log.query_text,
            response_text=chat_log.response_text,
            recommendations=recommendations,
            created_at=chat_log.timestamp
        )

    except Exception as e:
        db.rollback()
        traceback.print_exc()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error executing chat query: {str(e)}"
        )